;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-delete-char
	c-electric-colon
	c-electric-paren
	c-electric-pound
	c-electric-slash
	calendar-scroll-left
	electric-newline-and-maybe-indent
	forward-sentence
	go-mode-insert-and-indent
	indent-for-tab-command
	kill-region
	markdown-exdent-or-delete
	message-tab
	ns-copy-including-secondary
	ns-prev-frame
	sgml-slash
	sp--self-insert-command
	sp-remove-active-pair-overlay
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	c-electric-semi&comma
	dired
	end-of-buffer
	handle-switch-frame
	mark-whole-buffer
	markdown-demote
	save-some-buffers
	))
